apiVersion: v1
kind: Namespace
metadata:
  name: seperate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-media-pv-seperate
  namespace: seperate
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  nfs:
    path: /exports/smartpages/seperate/media
    server: 172.16.243.12
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-media-pvc
  namespace: seperate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  volumeName: sp-media-pv-seperate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: q3seperate
  namespace: seperate
spec:
  replicas: 4
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: q3seperate
    spec:
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: sp-media-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 51000
        fsGroup: 51001
        supplementalGroups:
          - 51001
      containers:
      - name: q3seperate
        # Pulls the default objectstorage image: $DOCKER_REG_FOR_SERVICES/ from Docker Hub
        image: mycluster.icp:8500/seperate/q3seperate
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: baca
        - name: POSTGRES_HOST
          value: seperatepostgres
        - name: POSTGRES_PORT
          value: '5432'
        securityContext:
          runAsUser: 51000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: media # must match the volume name, above
          mountPath: /app/media
          subPath: mlalgorithms

---
apiVersion: v1
kind: Service
metadata:
  name: q3seperate
  namespace: seperate
  labels:
    app: q3seperate
spec:
  ports:
    - port: 8060
  type: NodePort
  selector:
    app: q3seperate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-db-pv-seperate
  namespace: seperate
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /exports/smartpages/seperate/db
    server: 172.16.243.12
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-db-pvc
  namespace: seperate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: sp-db-pv-seperate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: seperatepostgres
  namespace: seperate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: seperatepostgres
    spec:
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: sp-db-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 51000
        fsGroup: 51001
        supplementalGroups:
          - 51001
      containers:
      - name: seperatepostgres
        # Pulls the default objectstorage image: $DOCKER_REG_FOR_SERVICES/ from Docker Hub
        image: mycluster.icp:8500/seperate/postgres:latest
        imagePullPolicy: Always
        env:
        - name: PGDATA
          value: '/var/lib/postgresql/data/pgdata'
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: baca
        securityContext:
          runAsUser: 51000
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: seperatepostgres
  namespace: seperate
  labels:
    app: seperatepostgres
spec:
  ports:
    - port: 5432
  type: ClusterIP
  selector:
    app: seperatepostgres