version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "baca"
    ports:
      - "5433:5432"
    user: "51000"
    volumes:
      - ./dataVolume/postgres:/var/lib/postgresql/data
  datascience:
    build: ./datascience
    image: datascience
    environment:
      DEBUG: "false"
      COMPOSE: "true"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "baca"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "0.0.0.0"
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    volumes:
      - ./dataVolume/media:/app/media
      - ./datascience/smartpackage:/app/smartpackage
      - ./datascience/datascience:/app/datascience
  webapi:
    build: ./webapi
    image: webapi
    environment:
      PORT: 10010
      ML_API_PROTOCOL: http
      ML_API_IP: localhost
      ML_API_PORT: 8060
    ports:
      - "10010:10010"
    volumes:
      - ./webapi/api:/usr/src/app/api
  frontend:
    build: ./frontend
    image: frontend
    environment:
      LOG_LEVEL: debug
      DEBUG: "false"
      API_PROTOCOL: http
      API_IP: localhost
      API_PORT: 10010
    ports:
      - "8000:8000"

